name: build_embedded
# Add secret to environment
env:
  PROJECT_SDK_SECRET: ${{secrets.PROJECT_SDK_SECRET}}
  PROJECT_SECRET: ${{secrets.PROJECT_SECRET}}
on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_embedded_secure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install ninja
      run: |
        sudo apt-get -y install ninja-build
    - name: Build
      run: |
        curl https://raw.githubusercontent.com/Cascoda/cascoda-sdk/master/etc/arm_gnu_toolchain_setup.sh | bash; source /etc/profile
        cd EXAMPLE
        chmod +x ./build_win_bin_ninja.sh
        ./build_win_bin_ninja.sh
        cd ../BATTLESHIP
        chmod +x ./build_win_bin_ninja.sh
        ./build_win_bin_ninja.sh
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: embedded_secured
        path: |
           ./EXAMPLE/build_win_bin/*/*.bin
           ./EXAMPLE/*.md
           ./EXAMPLE/*/*.md
           ./EXAMPLE/*/*/*.jpg
           ./EXAMPLE/*/*/*.PNG
           ./EXAMPLE/*/MT/*.knxproj
           ./BATTLESHIP/build_win_bin/*/*.bin
           ./BATTLESHIP/*.md
           ./BATTLESHIP/*/*.md
           ./BATTLESHIP/*/*/*.jpg
           ./BATTLESHIP/*/*/*.PNG
           ./BATTLESHIP/*/MT/*.knxproj
